### ISSUE TITLE
Blackmagic Macro triggered everytime from the beginning

### ISSUE THREAD

**Issue by Keksstar** [bitfocus/companion-module-atem#10]
When creating an Macro in Blackmagic ATEM with an "User Wait" Companion triggers the Macro everytime from the beginning, not where the Macro is actually….
So User Wait Macros can´t be used with Companion....

**Comment by krocheck** [comment]
This has been fixed for the next release (available in the current build) ... Run MACRO now has a dropdown to select between "Run" and "Run/Continue".  Its recommended to use the new 'Presets' that are available for Macros as they have feedback colors and dynamic text that reads the macro name from the ATEM.
