### ISSUE TITLE
Support for Atem Constellation 40 inputs 24 outs willing to test

### ISSUE THREAD

**Issue by ryandrby** [bitfocus/companion-module-atem#21]
**Describe the feature**
A clear and concise description of what the feature does

**Is this platform dependent (windows, mac, ..)?**
Explain

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

**Comment by krocheck** [comment]
This is a work-in-progress with the team that manages the upstream library.

**Comment by ryandrby** [comment]
If anyone has time to jump on this ASAP I would love to contribute or pay for their time.

Thanks,
Ryan

--
Ryan Durbin
Lambda Audio Visual Inc
Phone: (719) 629-7905
email: ryan@lambdaav.io

**Comment by krocheck** [comment]
I'm one of the main developers of the ATEM module and I own a Constellation.  Trust me, if it were that simple it would already be done.  There were some breaking changes in the v8 firmware (for all ATEM switchers) and we're dealing with how to handle backwards compatibility for those that don't wish to or can't upgrade their ATEMs.  It is not reasonable for Companion to dictate that only v8 firmware is supported.  If I didn't buy a Constellation, my other switchers would be on 7.5.2 for another 6 months minimum.

**Comment by ryandrby** [comment]
Oh interesting I didn’t know that, I’ve been using 2.0 with my constellation just in 4me mode with no issues and it’s been great, but that makes sense.

Thanks,
Ryan

--
Ryan Durbin
Lambda Audio Visual Inc
Phone: (719) 629-7905
email: ryan@lambdaav.io

**Comment by ryandrby** [comment]
8.0.1 had some major issues but 8.0.2 is much corrected, I talked with a few of the BMD guys and it’s working really well.

Thanks,
Ryan

--
Ryan Durbin
Lambda Audio Visual Inc
Phone: (719) 629-7905
email: ryan@lambdaav.io

**Comment by krocheck** [comment]
That's been my experience as well.  Its the underlying API that's the issue.  BMD makes it easy for themselves because their software has to match the exact firmware version on the switcher, but we can't guarantee that.  So there has to be detection and mitigation inline as they change how the software communicates with the switcher (because we're effectively emulating that, and we have to do it by reverse engineering because those spec's aren't published by BMD).

**Comment by ryandrby** [comment]
Totally get it, I’m excited to have functionality whenever you guys finish it and please I would love to help in any way that I can be helpful

**Comment by magicmister12** [comment]
hi! lol, no i'm not a developer, but i was really wondering if someone will make the magic happen and recode the app to run with more than a 1m/e switcher. 

thanks and good luck! stay save.

**Comment by Julusian** [comment]
Hi @magicmister12, this does work with other models.
Make sure you are running companion v2.1.0, and if you are not connected to your atem then select the model under the config so that the additional me are available to you

**Comment by magicmister12** [comment]
Wow, that are great news! Thanks for that super-fast response to my
question. I'll try tomorrow!

Bye

Julian Waller <notifications@github.com> schrieb am So., 30. Aug. 2020,
00:26:

**Comment by magicmister12** [comment]
Great! It works. Thanks's a lot for your help. Here is a very simple youtube video, how to set this up for the atem constellation 8k or other multi m/e mixers.
[](https://youtu.be/GPVgnZ6aVus)
