### ISSUE TITLE
Blackmagic ATEM Module - Macro Name on Button

### ISSUE THREAD

**Issue by Sade66** [bitfocus/companion-module-atem#22]
**Describe the feature**
Add the ability to automatically take the name of a specific Macro on an ATEM and make that the text on a button.

**Is this platform dependent (windows, mac, ..)?**
No.

**If documentation is required to implement, do you know where to find it?**
https://www.blackmagicdesign.com/developer/

**Usecases**
This would allow a user to have a page of macro buttons that update as new macros are made. This way the user doesn't have to mess with changing the button title each time they write over a macro.

**Comment by krocheck** [comment]
This is a thing in the v1.4 and v2.0 builds.  Best thing to do is use the button presets as they also have feedback info.
