### ISSUE TITLE
Companion on Blackmagic ATEM.  Connection lost

### ISSUE THREAD

**Issue by DrumDrummy** [bitfocus/companion-module-atem#23]
I've got a Stream Deck with Companion installed on PC to run a Blackmagic ATEM. Everything is on static IPs and when I initially setup everything works fine. Then when I power off Companion and then restart it (or turn everything off and reboot the next day etc) the Deck buttons appear but don't work and no feedback is happening (on Companion as well as the physical buttons). Companion is showing everything is connected and OK. All the IPs are correct but the bottons do nothing. No amount of restarting/rebooting the PC/ATEM/Software in various different orders makes any difference. The only way to solve is to go into the GUI and remap the buttons (ie drag the template buttons over to the Deck buttons again), Then it works fine (with feedback) until I close down (and try to restart) Companion again. No other software is running (ie StreamDeck/BM ATEM front end). If I do use the Stream Deck program with the Companion plugin, I get exactly the same problem. Any ideas?

**Comment by krocheck** [comment]
I believe this was resolved in the newer v2.0 builds.
