### ISSUE TITLE
Auto transition type and delay

### ISSUE THREAD

**Issue by jasonmotha** [bitfocus/companion-module-atem#24]
Hi,

Unsure  if this is a bug or if I am blind.

Is there a way to change the transition type between mix and dip? And also to change the transition time? I could do this with a macro but wondering if there is a native way.

Cheers

**Comment by krocheck** [comment]
Nope ... no way to do that at the moment.  I'll add it to the list.  Bury it in a high # macro for the time being.  You won't have feedback but it'll work.
