### ISSUE TITLE
Error on Dragging Preset to Button

### ISSUE THREAD

**Issue by krocheck** [bitfocus/companion-module-atem#28]
![image](https://user-images.githubusercontent.com/749812/65925956-794ba900-e3b8-11e9-8958-7d780d8eb56b.png)

Attempted to drag a preset onto a button.  Appears to occur for all presets in the catalog.

After clicking OK to the dialog, the preset does otherwise seem to apply correctly.

**Comment by Julusian** [comment]
@krocheck This should be good now
