### ISSUE TITLE
Select "Next Transition" type

### ISSUE THREAD

**Issue by stevespaw** [bitfocus/companion-module-atem#29]
We are getting so close on the ATEM to ditching macros. But we need a couple more functions.

 1. Be able to select the "auto/cut" transition "NEXT TRANSITION" from background to any of the keys in any combination. (and on any ME) 

![Annotation 2019-10-01 123934](https://user-images.githubusercontent.com/11045430/65985998-97f98080-e448-11e9-9237-1de2073b2dcd.png)

![Annotation 2019-10-01 124916](https://user-images.githubusercontent.com/11045430/65986818-44883200-e44a-11e9-9d8e-ea935e9503d9.png)

**Comment by Julusian** [comment]
This is available in latest 2.0 builds
