### ISSUE TITLE
Button functionality for all ATEM supersource parameters

### ISSUE THREAD

**Issue by T68** [bitfocus/companion-module-atem#31]
**Describe the feature**
As well as function for setting the box input source I would like to have the ability to also set enable, size, position and crop parameters for a supersource box. This would eliminate the need for a lot of ATEM-macros for us.

**Is this platform dependent (windows, mac, ..)?**
No it´s an ATEM thing

**If documentation is required to implement, do you know where to find it?**
Se supplied screenshot

**Usecases**
User wants to change an entire atem supersource setup (which boxes to enable, the size, position and crop and input) using one stream deck button. 
![supersource_setup](https://user-images.githubusercontent.com/2562120/65966814-eb77c880-e460-11e9-83a3-dd77dec65c2b.jpg)

**Comment by Julusian** [comment]
I'm thinking about how to split it up to not be too annoying to work with.

Perhaps an action for each of:
- Enable/Disable a box
- Set the box source (already exists)
- Set the box position & size & crop

This would mean that it wont be possible to change the position of a box without also having to specify the size and crop. Is this granular enough?

**Comment by T68** [comment]
Looks like the right way to do it! It was something like that I had in mind. Good to not have an action for everything .

**Comment by Julusian** [comment]
This is available in latest 2.0 builds
