### ISSUE TITLE
Blackmagic Atem DSK 2 not functioning

### ISSUE THREAD

**Issue by tperrett** [bitfocus/companion-module-atem#32]
Using a Blackmagic ATEM Television Studio (https://www.blackmagicdesign.com/products/atemtelevisionstudio) and using the DSK auto trans command for DSK 1, it works fine, select DSK 2 and it doesn't seem to work at all.

**Comment by Julusian** [comment]
@tperrett We need to know the versions as asked above to be able to look into this further for you.

**Comment by tperrett** [comment]
Hello

Thanks for your patience on this. Here is a link to a video of our setup with hopefully all the details you need included showing DSK 2 auto trans not working:
https://www.dropbox.com/s/h4xjlesg7zjjxxa/Companion%201.4%20Atem%20DSK%202%20Issue.MOV?dl=0 <https://www.dropbox.com/s/h4xjlesg7zjjxxa/Companion%201.4%20Atem%20DSK%202%20Issue.MOV?dl=0>

Companion 1.4
Blackmagic ATEM 8.0.2

Hope this helps clarify what is going on.
Best

Tim

tim perrett
on the phone: 07970 121906
by email: tim@timperrett.co.uk
online: www.timperrett.co.uk

timperrett is a trading name of 3540 Limited. Registered in England and Wales No. 10772897.
Registered Office: 30-34 North Street, Hailsham, East Sussex, BN27 1DW.

**Comment by Julusian** [comment]
Thanks for the extra info. That confirms that it is an incompatibility between your version of companion and atem software. 
Companion 1.4 only supports the atem up to v7.5.2.
v8.0.0 and v8.0.1 introduced some breaking protocol changes, one of which is the DSK auto command.

Your options are to either run companion 2.0, or downgrade your atem to 8.0.0 or lower.

**Comment by Julusian** [comment]
This is unrelated, but did you have to select a model in the settings for your device? If so, what did you choose?
We don't appear to have any specs defined for your model of atem, meaning it will think it has the wrong number of sources, keyers etc.

**Comment by Julusian** [comment]
Closing as this works in 2.0, and is a known limitation of 1.4
