### ISSUE TITLE
Atem change supersource box properties: different parameter-scale in Companion versus Atem 

### ISSUE THREAD

**Issue by T68** [bitfocus/companion-module-atem#34]
Hi!
I really appreciate the new functionality to set Atem Supersource parameters with a Companion action. Great work!

However there are a couple of small issues I hope can be adressed in future releases.

First: Companion and Atem uses different decimal scales,  so a size parameter 0.35 in Atem has to be 350 in Companion. This works but is a bit complicated, if you for example draw up a box setting in atem and want to program a button in Companion. All parameters has to be recalculated instead of just copied.

Second: the fields in the setting in companion are too small so you don´t see the full parameter.

![image](https://user-images.githubusercontent.com/2562120/67685757-f6f1dd00-f995-11e9-860e-878de49e9254.png)

**Comment by Julusian** [comment]
This is waiting on https://github.com/bitfocus/companion/pull/884 to allow for using decimal numbers.
Again I think that will be something I need to look at companion core to try and resolve.

**Comment by Julusian** [comment]
This is implemented in latest 2.0
