### ISSUE TITLE
ATEM 1 M/E Production Studio DSK 2 not functional via companion

### ISSUE THREAD

**Issue by mcreim** [bitfocus/companion-module-atem#38]
Starting with Firmware 8.x DSK 2 on blackmagic ATEM(and maybe other functions too) are not responding to companion.

**Comment by McHauge** [comment]
This is a know issue, and it has been fixed in companion V2.0

**Comment by mcreim** [comment]
Ok, I downloaded the (old) version via the webpage. I try to find 2.0

**Comment by McHauge** [comment]
https://builds.bitfocus.io/companion/

**Comment by mcreim** [comment]
Thank you :-) Maybe you can eventually put an actual link on the start page. :-)

**Comment by Julusian** [comment]
@McHauge is correct, 8.0+ is only supported in companion 2.0. Once I have finished up a few new bits, companion 2.0 will start to state what versions of atem firmware it supports, so in the future this should be less of an issue.

As this issue keeps on coming up, I think I need to look at adding something to the readme, or perhaps when submitting an issue.
