### ISSUE TITLE
More Auxs on PC for black magic

### ISSUE THREAD

**Issue by drproverb** [bitfocus/companion-module-atem#44]
Hello I am trying to use this with the Aux on the constilation as well as more inputs for PC is there anyway to use this I dont see any other option besides the 3 aux and 8 input

**Comment by Julusian** [comment]
This already works in the 2.0 builds, so you will need to update to get control of more outputs.

**Comment by drproverb** [comment]
this does not work for the consolation for 24 auxes and 40 inputs

love the software btw

**Comment by krocheck** [comment]
@drproverb Constellation is supported in the v2.0.0 dev/beta builds.

https://bitfocus.io/companion/download/builds/

I've been testing against it for months.

**Comment by drproverb** [comment]
Which version there is a lot of them

**Comment by krocheck** [comment]
Any of them (most recent at top) ... those are just the daily updates with changes as developers submit updates to the various modules.
