### ISSUE TITLE
Request: Dynamic Variable for Media Player Source Name

### ISSUE THREAD

**Issue by sakhaUAC** [bitfocus/companion-module-atem#46]
I'm looking for a way to dynamically change the name of a button to display the name of a Media Player source image.

The source image name is displayed in the "Change Media Player Source" dropdown menu, but is not available for use as a dynamic variable to modify button text. I don't see a way to be able to grab the name shown in the dropdown and use it elsewhere.

In the below example, I'd like to be able to make the button's text be "BeginShortly".

![vivaldi_2020-02-18_11-31-57](https://user-images.githubusercontent.com/61196972/74756270-4b211580-5242-11ea-972f-aab56992c4f3.png)

**Comment by sakhaUAC** [comment]
Seems to work as intended, thanks for the quick turnaround! Using build companion-2.0.0-5e2c920-2061

Are you noticing any performance difference with this build? I'm on the 32-key XL Stream Deck and while page transitions were near instant before updating, now it visibly updates each button individually in sequence when switching pages and takes about 1-1.5 seconds to fully transition.

While staying on the same page, all actions seem to have identical performance (instant response) as before so it's not a dealbreaker - the added functionality is worth staying for. It'd be nice to know though if it's due to this module update or something else.

**Comment by Julusian** [comment]
That will not be related to this, but take that over to either https://github.com/bitfocus/companion/pull/988 or a new issue there. I did make some changes to the streamdeck library the other day, but it should be faster especially for the xl.
What os are you on?
