### ISSUE TITLE
Sending actions to disconnected ATEM crashes Companion

### ISSUE THREAD

**Issue by bryce-seifert** [bitfocus/companion-module-atem#50]
To recreate:
-Connect ATEM, make sure it's "OK" in Companion.
-Disconnect ATEM power or network cable.
-Press a button that has an ATEM action.
-Full Companion crash, no error

In dev mode, this in the info being returned when following the above steps:
<img width="1303" alt="Screen Shot 2020-02-29 at 10 09 49 AM" src="https://user-images.githubusercontent.com/50299051/75611178-bccc4f80-5add-11ea-8606-ba769b532513.png">
<img width="653" alt="Screen Shot 2020-02-29 at 10 09 02 AM" src="https://user-images.githubusercontent.com/50299051/75611180-c05fd680-5add-11ea-87d5-01c03466bac1.png">

I first discovered this crash at the same time as this was happening, not sure if it's related. It seems to be disconnecting repeatedly and if the button press happened to be while it was disconnected it would crash Companion.

![screen_shot_2020-02-28_at_3 44 42_pm](https://user-images.githubusercontent.com/50299051/75611192-eab19400-5add-11ea-9aa5-f16143f9639b.png)

**Comment by Julusian** [comment]
This should log an error instead now.
The spamming of connections should be resolved by the connection library downgrade

**Comment by bryce-seifert** [comment]
Seems to be stable now after initial testing, no spamming or crashes.

**Comment by Julusian** [comment]
Closing as this appears resolved
