### ISSUE TITLE
Instance feedback for Macro 

### ISSUE THREAD

**Issue by studiovideo54** [bitfocus/companion-module-atem#8]
**Describe the feature**
Hi i need instance feedback for Macro Button like a change color for preview and program.

**Is this platform dependent (windows, mac, ..)?**
MAC

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

**Comment by krocheck** [comment]
This has been added for the next release (available in the current build).  It is recommended to use the new Macro presets to create any buttons for macros as they have dynamic text and feedback colors preset.
